### ISSUE TITLE
Install?

### ISSUE THREAD

**Issue by skistaddy** [davidnagli/Scratch-JS#23]
Are we going to use my Scratch-JS on npm for our install or script refs or what?

**Comment by davidnagli** [comment]
Our target audience usually doesn't have NPM, so I'm thinking of eventually making a web interface similar to Scratch

The website could have intermediate and advanced mode, where beginners have a drag and drop interface where they drag blocks but see the Scratch-JS generated side by side. This generated code can also be edited instead of only interacting with the drag and drop. Advanced mode is all typing and a preview of the resulting program (basically Cloud9 for Scratch-JS).


The website would also allow users to download the code along with the Scratch-JS dependencies.

**Comment by skistaddy** [comment]
A website would kinda defeat the purpose of the library. I was thinking they could instead reference the library similarly to jQuery. 
```
<script src="https://scratch.github.io/scratch-js.js></script>
```

**Comment by skistaddy** [comment]
Bump.

**Comment by davidnagli** [comment]
Let's use https://rawgit.com

Our dev URL: https://rawgit.com/Scratch-JS/Scratch-JS/master/index.min.js

**Comment by davidnagli** [comment]
When we release Scratch-JS-Beta-0.2 we can create a production CDN hosted URL for it.

**Comment by skistaddy** [comment]
K.
