### ISSUE TITLE
Reason for Commented Out Function?

### ISSUE THREAD

**Issue by skistaddy** [davidnagli/Scratch-JS#34]
https://github.com/Scratch-JS/Scratch-JS/blob/master/index.js#L514 is commented out, is it not ready yet, does it not work, or is it accidental?

**Comment by davidnagli** [comment]
It accidently left there during debugging when I switched `mouse.isDown` to use `document.addEventListener` instead of `document.onmousedown` [over here](https://github.com/Scratch-JS/Scratch-JS/blob/master/index.js#L371)

The commented lines were left there by accident. I'll remove them in the next commit.

**Comment by skistaddy** [comment]
K.
